spring:
  config:
    import: env.properties
  jpa:
    generate-ddl: true
    hibernate:
      show-sql: true
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    initialization-mode: always
    initialize: true
jwt_secret: ${JWT_SECRET}